spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmos?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rlarudrb119!

  jpa:
    database: mysql
    #    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        #        ddl-auto: update
        hbm2ddl:
          auto: update

application:
  security:
    jwt:
      secret-key: 903d39eb06940f1e043c0db2e775d31dc450e47afa75c38ec4dbdd23edd2185f446853b5e6e44c9c3ca2f865713ab29d183c6224e6b22368ad7e0f65059733b4
      expiration: 3600000