spring:
  datasource:
    url: jdbc:mysql://3.38.7.193:3306/mmos?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mmos
    password: rlarudrb119!

  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        hbm2ddl:
          auto: update

cloud:
  aws:
    s3:
      bucket: m-mos
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

application:
  security:
    jwt:
      secret-key: 903d39eb06940f1e043c0db2e775d31dc450e47afa75c38ec4dbdd23edd2185f446853b5e6e44c9c3ca2f865713ab29d183c6224e6b22368ad7e0f65059733b4
      expiration: 3600000